
export const CARD_SUIT_SPADE = 'CARD_SUIT_SPADE';
export const CARD_SUIT_CLUB = 'CARD_SUIT_CLUB';
export const CARD_SUIT_HEART = 'CARD_SUIT_HEART';
export const CARD_SUIT_DIAMOND = 'CARD_SUIT_DIAMOND';

export const cardValues = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];

export const cards = [
  {value: 'A', suit: CARD_SUIT_SPADE},
  {value: '2', suit: CARD_SUIT_SPADE},
  {value: '3', suit: CARD_SUIT_SPADE},
  {value: '4', suit: CARD_SUIT_SPADE},
  {value: '5', suit: CARD_SUIT_SPADE},
  {value: '6', suit: CARD_SUIT_SPADE},
  {value: '7', suit: CARD_SUIT_SPADE},
  {value: '8', suit: CARD_SUIT_SPADE},
  {value: '9', suit: CARD_SUIT_SPADE},
  {value: '10', suit: CARD_SUIT_SPADE},
  {value: 'J', suit: CARD_SUIT_SPADE},
  {value: 'Q', suit: CARD_SUIT_SPADE},
  {value: 'K', suit: CARD_SUIT_SPADE},
  {value: 'A', suit: CARD_SUIT_CLUB},
  {value: '2', suit: CARD_SUIT_CLUB},
  {value: '3', suit: CARD_SUIT_CLUB},
  {value: '4', suit: CARD_SUIT_CLUB},
  {value: '5', suit: CARD_SUIT_CLUB},
  {value: '6', suit: CARD_SUIT_CLUB},
  {value: '7', suit: CARD_SUIT_CLUB},
  {value: '8', suit: CARD_SUIT_CLUB},
  {value: '9', suit: CARD_SUIT_CLUB},
  {value: '10', suit: CARD_SUIT_CLUB},
  {value: 'J', suit: CARD_SUIT_CLUB},
  {value: 'Q', suit: CARD_SUIT_CLUB},
  {value: 'K', suit: CARD_SUIT_CLUB},
  {value: 'A', suit: CARD_SUIT_HEART},
  {value: '2', suit: CARD_SUIT_HEART},
  {value: '3', suit: CARD_SUIT_HEART},
  {value: '4', suit: CARD_SUIT_HEART},
  {value: '5', suit: CARD_SUIT_HEART},
  {value: '6', suit: CARD_SUIT_HEART},
  {value: '7', suit: CARD_SUIT_HEART},
  {value: '8', suit: CARD_SUIT_HEART},
  {value: '9', suit: CARD_SUIT_HEART},
  {value: '10', suit: CARD_SUIT_HEART},
  {value: 'J', suit: CARD_SUIT_HEART},
  {value: 'Q', suit: CARD_SUIT_HEART},
  {value: 'K', suit: CARD_SUIT_HEART},
  {value: 'A', suit: CARD_SUIT_DIAMOND},
  {value: '2', suit: CARD_SUIT_DIAMOND},
  {value: '3', suit: CARD_SUIT_DIAMOND},
  {value: '4', suit: CARD_SUIT_DIAMOND},
  {value: '5', suit: CARD_SUIT_DIAMOND},
  {value: '6', suit: CARD_SUIT_DIAMOND},
  {value: '7', suit: CARD_SUIT_DIAMOND},
  {value: '8', suit: CARD_SUIT_DIAMOND},
  {value: '9', suit: CARD_SUIT_DIAMOND},
  {value: '10', suit: CARD_SUIT_DIAMOND},
  {value: 'J', suit: CARD_SUIT_DIAMOND},
  {value: 'Q', suit: CARD_SUIT_DIAMOND},
  {value: 'K', suit: CARD_SUIT_DIAMOND},
];